language: node_js
node_js:
- '10' 
sudo: enabled
install:
- npm install
script:
- 'set -ev;
if [ ${TRAVIS_EVENT_TYPE} = "cron" ]; then
  npm install -g electrode-native;
  ern;
  node setup-dev;
  ern platform use 1000.0.0;
  npm run coverage:ci;
fi'