trigger:
  - master

jobs:
  - job: Windows
    pool:
      vmImage: 'win1803'
    steps:
      - template: azure/templates/unit-tests.yml
  - job: macOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - template: azure/templates/unit-tests.yml
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: azure/templates/unit-tests.yml
